services:
  agent:
    image: wgcloud-agent:latest
    pid: host                   # ← 新增：共享宿主 PID 命名空间
    privileged: true
    network_mode: "host"
    environment:
      - base.serverUrl=http://192.168.31.195:9999
      - base.bindIp=192.168.31.195
      - base.wgToken=wgcloud
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
      - /data/wgcloud/agent/logs:/app/log
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.pid:/var/run/docker.pid