name: Delete Old Packages

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old lins-server versions
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          versions=$(gh api /repos/${{ github.repository }}/packages/container/lins-server/versions --jq '.[].id' | tail -n +6)
          for v in $versions; do
            gh api -X DELETE "/repos/${{ github.repository }}/packages/container/lins-server/versions/$v"
          done

      - name: Delete old lins-agent versions
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          versions=$(gh api /repos/${{ github.repository }}/packages/container/lins-agent/versions --jq '.[].id' | tail -n +6)
          for v in $versions; do
            gh api -X DELETE "/repos/${{ github.repository }}/packages/container/lins-agent/versions/$v"
          done
